FROM python:3

#WORKDIR /usr/src/app

COPY requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

#COPY . .

#CMD [ "python", "./your-daemon-or-script.py" ]

########################################################
#          sudo docker build -t pyenv:1.0 .            #
########################################################


########################################################
#          sudo docker rmi pyenv:1.0                   #
########################################################
